### PR TITLE
test:  improve controller topic unit test cov

### PR DESCRIPTION
**Pull request by sinchang**
Ref: issue #61 

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)
test

### CODE REVIEW

**Comment by JacksonTian** [comment]
额 跟我的工作重复了。

**Comment by sinchang** [comment]
@JacksonTian 你的先合，我这边再补充测试用例。

**Comment by JacksonTian** [comment]
我的已经先 merge 了。

**Comment by sinchang** [comment]
ready to merge cc @JacksonTian

**Pull request merged**
